server:
  port:
    8082
application:
  name: citizen-service


spring:
  datasource:
   url: jdbc:h2:mem:testdb12
  driverClassName: org.h2.Driver
  username: sa
  password:
  jpa:
   database-platform: org.hibernate.dialect.H2Dialect